# Logstash can import from log files, csv, json, MySql, s3, beats, kafka and many many more...
# Logstash can export data to elasticsearch, aws, hadoop, mongodb and many many more...

# Configure logstash - copy logstash.conf to /etc/logstash/conf.d/logstash.conf
# sudo /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
# Edit file: preview edited file right now

### Get catalog of indicies
GET  http://localhost:9200/_cat/indices?v

###
GET http://localhost:9200/logstash-2020.11.12-000001/_search

###
GET http://localhost:9200/logstash-2020.11.12-000001/_mapping

### So far we installed logstash, used it to import data from access_log and created index

## How logstash parses logs? Grok
# Grok debug tool: https://grokdebug.herokuapp.com/
# Grok can parse logs of: # Nginx, IIS, MongoDB  and many more...
# Grok can perform GeoLocation mapping
# Grok logstash patterns: https://github.com/logstash-plugins/logstash-patterns-core/tree/master/patterns


### Logstash Input Plugins
# Heartbeat
DELETE http://localhost:9200/heartbeat-epoch
#sudo /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/logstash-input-plugins/heartbeat/heartbeat-sequence.conf
###
GET http://localhost:9200/heartbeat-sequence/_search

### Generate - userful for testing elasticsearch and logstash
DELETE http://localhost:9200/generator
#sudo /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/logstash-input-plugins/generator/generator.conf
###
GET http://localhost:9200/generator/_search

### HTTP Poller input plugin
#Pulls http peridically and saves response to elasticsearch
# sudo /usr/share/logstash/bin/logstash --path.settings /etc/logstash/ -f /etc/logstash/conf.d/logstash-input-plugins/http-poller/http-poller.conf

GET http://localhost:9200/http-poller-api/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "size": 1,
  "sort": [
    {
      "@timestamp": {
        "order": "desc"
      }
    }
  ]
}

###
GET http://localhost:9200/http-poller-es-health/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  },
  "size": 1,
  "sort": [
    {
      "@timestamp": {
        "order": "desc"
      }
    }
  ]
}

### Other input plugins
### Dead letter queue
# store in a file all not processed inputs - ex. due to parse error: TEST->integer etc.

# Twitter input plugin
# Syslog
# Hadoop
# Apache Kafka
# Apache Spark
# But...
# MongoDB - No official input plugin - https://github.com/phutchins/logstash-input-mongodb - is dead
# MongoDB - there is output plugin
